### ISSUE TITLE
404 on refresh

### ISSUE THREAD

**Issue by R3D2** [hjalmar/svelte-standalone-router#2]
If I hit something else than the homepage, I have an error page.
He makes sense for me, but I wanted to be sure that I did implement it correctly!

Thanks for the work that you put it out in this project ! Very great !

**Comment by hjalmar** [comment]
What server are you running? Don't forget to funnel all request to the root. e.g enable it for a SPA. If you are running the default svelte template, at the bottom of the readme it explains how to enable it in package.json with the --single flag.

**Comment by R3D2** [comment]
Ok, for the dev ! Got it, but it will work as a static website ?

**Comment by hjalmar** [comment]
Yes! Static in sense of i will work after bundle. However the content is dynamic so if you want play nice with searchengines you either want some static sitegenerator instead or ssr it yourself. 

But to host it just make sure you rewrite all request to root/index if you use something like apache or nginx. For github pages you do a bit of hack to simulate a SPA by utilizing its error fallback. A quick google would help you out with that.
